name: Create GitHub Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: ./

  generate_major_tag:
    name: Generate Major Tag

    runs-on: ubuntu-latest

    outputs:
      MAJOR_TAG: ${{ steps.generate-tag-step.outputs.MAJOR_TAG }}

    steps:
      - name: Setup NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Generate Major Tag
        id: generate-tag-step
        run: node -e "console.log('MAJOR_TAG='+'$TAG_NAME'.split('.')[0])" >> "$GITHUB_OUTPUT"
        env:
          TAG_NAME: ${{ github.ref_name }}

  update_latest:
    name: Update Latest Tag

    runs-on: ubuntu-latest
    needs: generate_major_tag

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config user.name "$USER_NAME"
          git config user.email "$EMAIL"
        env:
          USER_NAME: manferlo81
          EMAIL: manferlo81@gmail.com

      - name: Update Major Tag
        run: git tag $MAJOR_TAG -f
        env:
          MAJOR_TAG: ${{ needs.generate_major_tag.outputs.MAJOR_TAG }}

      - name: Push Tags
        run: git push --tags -f
