name: Create GitHub Release

on:
  push:
    tags:
        - 'v*'

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: ./
        with:
          latest: ${{ contains(github.ref_name, '.') }}
