name: Create GitHub Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: ./

  update_latest:
    name: Update Latest Tag

    needs: create_release

    permissions:
      contents: write
      actions: read

    uses: ./.github/workflows/update-latest.yml
    with:
      user-name: manferlo81
      email: manferlo81@gmail.com
