name: Create GitHub Release

on:
  push:
    tags:
        - 'v*'

jobs:
  create_release:
    name: Create GitHub Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: ./
        with:
          latest: ${{ contains(github.ref_name, '.') }}

  update_latest:
    name: Update Latest Tag

    runs-on: ubuntu-latest
    if: contains(github.ref_name, '.')

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Config Git
        run: |
          git config user.name "$USER_NAME"
          git config user.email "$EMAIL"
        env:
          USER_NAME: manferlo81
          EMAIL: manferlo81@gmail.com

      - name: Generate Major Tag
        id: generate-tag-step
        run: node -e "console.log('MAJOR_TAG='+process.argv[1].split('.')[0])" "$TAG_NAME" >> "$GITHUB_OUTPUT"
        env:
          TAG_NAME: ${{ github.ref_name }}

      - name: Update Major Tag
        run: git tag $MAJOR_TAG -f
        env:
          MAJOR_TAG: ${{ steps.generate-tag-step.outputs.MAJOR_TAG }}

      - name: Push Tags
        run: git push --tags -f
