name: Update Major Version (v0)

on:
  workflow_dispatch:

env:
  tag: v0

jobs:
  update_major_version:
    name: Update Major Version

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config user.name "${{ env.USER_NAME }}"
          git config user.email "${{ env.EMAIL }}"
        env:
          USER_NAME: manferlo81
          EMAIL: manferlo81@gmail.com

      - name: Update Major Tag
        run: git tag ${{ env.tag }} -f

      - name: Push Tags
        run: git push --tags -f
