name: Update Action Latest Tag

on:
  workflow_call:
    inputs:
      user-name:
        description: Git user.name
        type: string
        required: true
      email:
        description: Git user.email
        type: string
        required: true

jobs:
  generate_major_tag:
    name: Generate Major Tag
    uses: ./.github/workflows/generate-major.yml

  update_latest:
    name: Update Latest Tag

    runs-on: ubuntu-latest
    needs: generate_major_tag

    permissions:
      contents: write
      actions: write

    env:
      MAJOR_TAG: ${{ needs.generate_major_tag.outputs.major-tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config Git
        run: |
          git config user.name "$USER_NAME"
          git config user.email "$EMAIL"
        env:
          USER_NAME: ${{ inputs.user-name }}
          EMAIL: ${{ inputs.email }}

      - name: Update Major Tag
        run: git tag -f $MAJOR_TAG ${{ github.ref_name }}

      - name: Push Tags
        run: git push origin $MAJOR_TAG -f
